version: '2.2'

services:
  app:
    build:
      context:  ./app
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 4000
    entrypoint: ./entrypoint.sh

  postgres:
    image: postgres:11.1-alpine
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - app
